### ISSUE TITLE
What is the publish site url?

### ISSUE THREAD

**Issue by garster** [ucsb/campus-cloud-docs#1]
Please edit the repo description and enter the published website url. This would be useful for anyone browsing the repos and wants to see the published content.

Is it "https://ucsb.github.io/campus-cloud-docs/"? We can do a custom domain like https://cloud.ucsb.edu/. I can help set that up if you like.

**Comment by jwoods-ucsb** [comment]
@garster I was waiting for the custom domain before adding the published site url to the repo. We have published, so I am adding it now.
